server:
  port: 15080
spring:
  servlet:
    multipart:
      # 1gb
      max-file-size: 1073741824
      max-request-size: 1073741824
      enabled: true

  profiles:
    include:
      - redis
      - mp
      - log
      - wx
      - thymeleaf
  application:
    name: zyb
  datasource:
    name: mall
    url: jdbc:mysql://39.98.142.99:33221/zyb?useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: OnlinezuozuoCreated.mysql.zyb
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最大链接数
      maximum-pool-size: 50
      # 客户端等待连接池连接的最大毫秒数
      connection-timeout: 10000
      # 最小空闲链接数
      minimum-idle: 5
      #允许连接在连接池中空闲的最长时间
      idle-timeout: 600000
      # 新建链接是判断
      connection-init-sql: SELECT 1

logging:
  file: log/zyb_mall.log
  level:
    root: INFO
    com:
      yiring:
        jg: debug
      ibatis: debug
    org:
      springframework:
        web: DEBUG
        jdbc: DEBUG


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  # MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名，注册后在 Mapper 对应的 XML 文件中可以直接使用类名，而不用使用全限定的类名
  type-aliases-package: com.yiring.jg.pm.pojo.entity
  configuration:
    # 数据库表与实体类的驼峰命名自动转换
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
