server:
  port: 8080
#  serverTimezone: GMT+8
spring:
  datasource:
    name: security_api
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    # mysql驱动8.x以上需要设置时区
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=GMT%2B8
#    serverTimezone: GMT+8
#    time-zone: GMT+8
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis:
  configLocation: classpath:/mybatis-config.xml
  typeAliasesPackage: com.tx.pojo.entity
  mapperLocations: classpath:mapper/*.xml
