server:
  port: 8088
spring:
  application:
    name: old-springboot-service
  datasource: 
    name: lejia
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://gz-cdb-ild273wn.sql.tencentcdb.com:61377/sany_truck?useUnicode=true&characterEncoding=utf8&max_allowed_packet=16M&allowMultiQueries=true
    username: sanydevtest
    password: sanydevtest@2019
  jackson:
    serialization:
      indent-output: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

mybatis: 
    configLocation: classpath:/mybatis-config.xml
    type-aliases-package: com.navinfo.truck.**.**.domain
    mapper-locations: classpath:mapper/*.xml
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

logging:
  level:
    root: INFO
    com:
      navinfo.truck: debug
      ibatis: debug
    org.springframework:
      web: DEBUG
      jdbc: DEBUG
  path: log/old-service.log